lib/tasks/clear.rake

Implemented following, some of it is commented out:
https://github.com/bitzlato/peatio/issues/7

Implement clear:market task

---

Gemfile
Gemfile.lock

https://github.com/amazing-print/amazing_print

Add amazing_print gem for AMAZING DEBUG!

---

docs/api/websocket_api.md

- Добавлен раздел `Working with orders`
- Автоформатирование

Doc: add info about working with orders through websocket

---

app/api/v2/entities/deposit.rb
app/jobs/cron/remove_invoiced_deposits.rb
app/models/deposit.rb
app/workers/daemons/cron_job.rb
db/migrate/20210827090805_add_expires_at_field_to_deposit.rb
db/structure.sql

feat: set expires_at value for invoiced deposit in migration
feat: add job that removes expired deposits

feat: add field expires_at in deposit entity

---

docs/api/websocket_api.md

- Добавлен пример подключения к приватному каналу используя API key
- Удалена информация об использовании jwt токена

Doc: connection to the private ws channel using the API key

---

app/gateways/bitzlato_gateway.rb
app/models/beneficiary.rb
app/models/withdraw.rb
spec/api/v2/account/beneficiaries_spec.rb
spec/api/v2/management/beneficiaries_spec.rb
spec/factories/beneficiaries.rb
spec/models/withdraw_spec.rb

Это первая часть (просто проверка без дерганья bitzlato db) для таска
[Проверять наличие public_name перед созданием бенефициара из фронта](https://github.com/bitzlato/peatio/issues/98)

Beneficiary and withdraw validate address

---

config/seed/wallets.yml

При wallets.balance = nil ломается liza.

Set not null balance in wallets seed

---

app/models/deposit.rb
app/models/withdraw.rb
db/migrate/20210910085149_add_is_locked_to_deposits.rb
db/migrate/20210910085819_add_is_locked_to_withdraws.rb
db/structure.sql
lib/tasks/accounts.rake

Resolves: https://github.com/bitzlato/peatio/issues/69

Add is_locked for deposits and withdraws

---

app/jobs/cron/currency_pricer.rb
app/models/market.rb
app/services/currency_services/price.rb
app/workers/daemons/cron_job.rb
config/application.rb
config/currencies.yml
config/seed/currencies.yml
db/structure.sql
spec/services/currency_services/price_spec.rb

Resolves: https://github.com/bitzlato/peatio/issues/108

Add CurrencyPricer

---

app/api/v2/mount.rb
docs/api/peatio_user_api_v2.md
docs/api/swagger/user_api.json
docs/api/websocket_api.md

fix: change user api title

---

app/api/v2/account/balances.rb
app/api/v2/account/beneficiaries.rb
app/api/v2/account/deposits.rb
app/api/v2/account/internal_transfers.rb
app/api/v2/account/withdraws.rb
app/api/v2/entities/beneficiary.rb
app/api/v2/entities/deposit.rb
app/api/v2/entities/withdraw.rb
app/api/v2/market/named_params.rb
app/api/v2/market/orders.rb
app/api/v2/public/currencies.rb
app/api/v2/public/markets.rb

Fixes: https://github.com/bitzlato/peatio/issues/93

Fix swagger validation errors

---

app/models/currency.rb

Fix currency icon_id

---

config/currencies.yml
config/database.yml
config/deploy/sandbox.rb
config/environments/sandbox.rb
config/influxdb.yml
config/initializers/bugsnag.rb
config/secrets.yml

Fixes: https://github.com/bitzlato/ansible/issues/84

Enable deposit_coin_address worker for testnets in sandbox

---

.rubocop.yml
app/jobs/cron/payment_address_balancer.rb

See: https://github.com/bitzlato/ansible/issues/84

Enable PaymentAddressBalancer for sandbox

---

config/deploy/sandbox.rb

See: https://github.com/bitzlato/ansible/issues/84

Enable blockchain daemon for sanbox

---

app/api/v2/entities/currency.rb
app/jobs/cron/collector.rb
app/jobs/cron/gas_price_checker.rb
app/workers/daemons/cron_job.rb
config/application.rb
config/blockchains.yml
db/migrate/20210924153647_add_high_transaction_price_at_to_blockchains.rb
db/structure.sql
spec/jobs/cron/gas_price_checker_spec.rb

Resolves: https://github.com/bitzlato/peatio/issues/104

Disable withdraw when gas price is too expensive

---

app/models/account.rb
app/models/order.rb
app/services/withdrawer.rb
config/seed/currencies.yml
spec/models/account_spec.rb

Fixes: https://github.com/bitzlato/peatio/issues/156

Fix exception handling in Withdrawer

---

app/models/payment_address.rb

https://app.bugsnag.com/bitzlato/peatio/errors/61891ece58ba250008f3c199?filters[event.since]=30d&filters[error.status]=open

Hotfix. Remove uniqnuess validation for blockchain

---

app/jobs/cron/bargainer_job.rb
app/models/order_ask.rb
app/models/order_bid.rb
app/services/bargainer.rb
app/workers/amqp/order_processor.rb
app/workers/daemons/cron_job.rb

Resolves: https://github.com/bitzlato/peatio/issues/235

Add bargainer

---

app/jobs/cron/bargainer_job.rb
app/services/bargainer.rb
config/deploy/sandbox.rb

See: https://github.com/bitzlato/peatio/issues/235

Add price and volume deviations to bargainer

---

app/models/order.rb
app/services/bargainer.rb
app/workers/daemons/bargainer_job.rb
config/application.rb
config/bargainers.yml
spec/services/bargainer_spec.rb

Resolves: https://github.com/bitzlato/peatio/issues/258

Enable bargainer for all markets

---

app/gateways/abstract_gateway.rb
app/gateways/ethereum_gateway.rb
app/gateways/ethereum_gateway/abstract_command.rb
app/gateways/ethereum_gateway/approver.rb
app/gateways/ethereum_gateway/gas_estimator.rb
app/models/blockchain_approval.rb
app/models/deposit.rb
app/models/payment_address.rb
app/services/blockchain_service.rb
config/initializers/peatio_transaction.rb
config/seed/blockchains.yml
config/seed/currencies.yml
db/migrate/20211019140943_add_allowance_enabled_to_blockchains.rb
db/migrate/20211026141101_create_blockchain_approvals.rb
db/structure.sql
spec/gateways/ethereum_gateway/approver_spec.rb
spec/gateways/ethereum_gateway_spec.rb

See: https://github.com/bitzlato/peatio/issues/197

Approve fee wallet for payment addresses with deposit

---

db/structure.sql
lib/tasks/balances.rake

See: https://github.com/bitzlato/peatio/actions/runs/1474369363

Fix balances:check rake task

---

app/api/v2/entities/account.rb
app/api/v2/entities/currency.rb
db/migrate/20211203102904_change_default_group_for_members.rb
db/structure.sql
spec/api/v2/account/balances_spec.rb

See: https://github.com/bitzlato/peatio/issues/285

Add withdrawal limits to API account entity

---

app/models/account.rb
app/workers/amqp/order_processor.rb

Resolves: https://github.com/bitzlato/peatio/issues/304

Don't send CannotLockFundsError to ETS in OrderProcessor

---

app/models/payment_address.rb
app/workers/daemons/collector.rb
spec/workers/daemons/collector_spec.rb

Fixes: https://github.com/bitzlato/peatio/issues/314

Fix collection after refueling

---

app/services/blockchain_service.rb
spec/factories/wallet.rb
spec/services/blockchain_service_spec.rb
spec/support/stub_ethereum.rb

Fixes: https://github.com/bitzlato/peatio/issues/328

Fix deposit withdrawals

---

app/api/v2/account/beneficiaries.rb
config/bargainers.yml
config/seed/blockchains.yml
config/seed/markets.yml
lib/tasks/seed.rake

На Sandbox и Development бенефициар активируется любым пинкодом.

Sandbox без 2FA и емйлов

---

app/api/v2/account/deposits.rb
app/api/v2/admin/deposits.rb
app/api/v2/entities/payment_address.rb
app/api/v2/validations.rb
app/gateways/abstract_gateway.rb
app/gateways/bitcoin_cash_gateway.rb
app/models/payment_address.rb
spec/api/v2/account/deposits_spec.rb

See: https://github.com/bitzlato/peatio/issues/107

Remove address_format parameter

---

db/migrate/20220131124813_compact_orders_func.rb
db/structure.sql

Fixes: https://github.com/bitzlato/peatio/issues/355

Fix compact_orders SQL-function

---

app/models/beneficiary.rb
app/models/currency.rb
db/migrate/20180529125011_replace_id_to_code.rb
db/migrate/20200909083000_remove_default_position_value_from_currencies_and_markets.rb
db/migrate/20210810202928_compare_money_currency_properties.rb
db/migrate/20211227134747_add_blockchain_currency_id_to_beneficiaries.rb

See: https://github.com/bitzlato/peatio/issues/107

Add ignored columns for Beneficiary and Currency
